apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: federation-controller-manager
  namespace: federation
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: federation-controller-manager
      labels:
        app: federated-cluster
        module: federation-controller-manager
    spec:
      containers:
      - name: controller-manager
        image: kelseyhightower/federation-controller-manager:1.3.0-2
        args:
          - --master=https://federation-apiserver:443
          - --dns-provider=google-clouddns
          - --federation-name=federation
          - --zone-name=federation.com.
          - --v=2
        ports:
          - containerPort: 443
            name: https
          - containerPort: 8080
            name: local
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
